OP-1189 | Validate inventory
informatici/openhospital-core pull request #1401
Opened 2024-09-09 11:09 UTC by ArnaudFonzam

2024-09-12 14:57 UTC, mwithi commented
Please resolve conflicts after #1400

2024-09-12 17:30 UTC, mwithi commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +										medDescriptionForUpdate = medDescriptionForUpdate + " "+medical.getDescription()+" lot code "+lot+" and qty :"+mainStoreQty+"/";
Also, the last "/" is meant to be "\n" (new line)?

```suggestion
										medDescriptionForUpdate = medDescriptionForUpdate + " " + medical.getDescription() + " lot code " + lot + " and qty : " + mainStoreQty + "/";
```

2024-09-12 17:30 UTC, mwithi commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +									medDescriptionForNew = medDescriptionForNew + " "+medical.getDescription()+" lot code "+lot+" and qty :"+mainStoreQty+"/";
Same here?

```suggestion
									medDescriptionForNew = medDescriptionForNew + " " + medical.getDescription() + " lot code " + lot + " and qty : " + mainStoreQty + "/";
```

2024-09-12 17:31 UTC, mwithi commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +			errors.add(new OHExceptionMessage(MessageBundle.formatMessage("angal.inventory.theoreticalqtyhavebeenupdatedforsomemedical.msg", medDescriptionForNew)));
Same bundle here?

2024-09-13 07:06 UTC, ArnaudFonzam commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +			errors.add(new OHExceptionMessage(MessageBundle.formatMessage("angal.inventory.theoreticalqtyhavebeenupdatedforsomemedical.msg", medDescriptionForNew)));
yes but with different param

2024-09-13 07:44 UTC, mwithi commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +			errors.add(new OHExceptionMessage(MessageBundle.formatMessage("angal.inventory.theoreticalqtyhavebeenupdatedforsomemedical.msg", medDescriptionForNew)));
ok, but they are two different things... or at least if the message is the same you could combine `medDescriptionForUpdate` and `medDescriptionForNew` in one message. Also, I was asking if you meant to list them as new lines, for which end endline character is not "/" but "\n"

2024-09-18 12:31 UTC, dbmalkovsky commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +			errors.add(new OHExceptionMessage(MessageBundle.formatMessage("angal.inventory.theoreticalqtyhavebeenupdatedforsomemedical.msg", medDescriptionForUpdate)));
if the message text includes parameters then the name of the msg should end with `.fmt.msg` per project standards.

2024-10-03 19:24 UTC, mwithi commented on src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java
> +								mov.getLot());
Please keep it separated anyway, for more code readability:
```suggestion
				// TODO: to decide if to give control to the user about this
				double realQty = mainStoreQty;
				MedicalInventoryRow newMedicalInventoryRow = new MedicalInventoryRow(null, mainStoreQty, realQty, inventory, medical,
								mov.getLot());
```

2024-10-04 07:00 UTC, mwithi requested changes
LGTM. Thanks a lot! (test are failing for another problem not related to this PR)

2024-10-04 07:00 UTC, mwithi approved these changes

2024-10-04 07:02 UTC, merged