OH2-396 | Add a lock mechanism in all the remaining entities without it
informatici/openhospital-core pull request #1432
Opened 2024-10-09 10:48 UTC by SilverD3

See OH2-396

I skipped `MedicalWard` as many tests are failing when I add the `lock` (`@Version`) property in that entity. I investigated and I realized that we need to refactor a lot of code `MedicalStokcIoOperations` to make `MedicalWard` entity support `lock` mechanism.

So if it's really needed, we'll open another issue for that.

2024-10-09 13:07 UTC, mwithi commented on sql/step_a112_add_missing_lock_columns.sql
column names are UPPERCASE in this project

2024-10-10 14:43 UTC, SilverD3 commented on sql/step_a112_add_missing_lock_columns.sql
They're stored in lowercase in the DBMS, but okay. Let's use uppercase

2024-10-10 21:34 UTC, mwithi commented on sql/step_a112_add_missing_lock_columns.sql
table names are lowercase (if `lower_case_table_names = 1`) but fields should be created as specified in the script

2024-10-11 07:18 UTC, mwithi commented
> So if it's really needed, we'll open another issue for that.

Created OH2-409

2024-10-11 07:22 UTC, mwithi commented on sql/step_a112_add_missing_lock_columns.sql
missing changes on step_04 and demo_data scripts

2024-10-22 11:12 UTC, mwithi commented on sql/step_a112_add_missing_lock_columns.sql
> +
Remove trailing empty lines

```suggestion
```

2024-10-22 11:13 UTC, mwithi commented on sql/step_04_all_following_steps.sql
> +source step_a112_add_missing_lock_columns.sql;
Please rename it as probably been merged before OP-1310
```suggestion
source step_a111_add_missing_lock_columns.sql;
```

2024-10-22 11:15 UTC, mwithi commented on sql/step_a112_add_missing_lock_columns.sql
Rename to `step_a111_add_missing_lock_columns.sql`

2024-10-22 11:16 UTC, mwithi requested changes
Add some comments, and waiting for updated `load_data_demo.sql`

2024-10-24 09:57 UTC, mwithi approved these changes

2024-10-28 20:05 UTC, merged