OP-247 Method ambiguity
informatici/openhospital-core pull request #194
Opened 2020-08-31 11:37 UTC by dbmalkovsky

Per [OP-247](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/OP-247) add new method that doesn't require the casting of null to `BillItems` to get all items.   The new method is `getAllBills(dateFrom, dateTo)`.   

Also added junit tests for both methods.

2020-08-31 21:32 UTC, mwithi requested changes
the proposed change duplicates an already existing method at line 291.

was it compiling?

2020-08-31 21:32 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +
Is it not the same as src/main/java/org/isf/accounting/service/AccountingIoOperations.java:291 ?

I think this was the coding history:

1. getBills(GregorianCalendar dateFrom, GregorianCalendar dateTo)
2. getBills(GregorianCalendar dateFrom, GregorianCalendar dateTo, Patient patient)
3. getBills(GregorianCalendar dateFrom, GregorianCalendar dateTo, BillItem billItem)

Methods 2. and 3. should be renamed in a more expressive way, as well as any other "getBills" ones.

Note that refactoring on `core` may affect `gui` as the latter use `manager` packages as endpoints

2020-09-01 11:46 UTC, mwithi approved these changes
Apart some suggestion that may be taken in consideration or not it LGTM.

2020-09-01 11:46 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	public ArrayList<Bill> getBillsByDate(GregorianCalendar dateFrom, GregorianCalendar dateTo) throws OHServiceException {
Nice the idea to add @deprecate, for this method I would suggest `getBillsBetweenDates` ('byDate' would suggest one single date)

2020-09-01 11:46 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	public ArrayList<BillPayments> getPaymentsForPatient(GregorianCalendar dateFrom, GregorianCalendar dateTo, Patient patient)
Nice the idea to add @deprecate, for this method I would suggest `getPaymentsBetweenDatesWherePatient`

2020-09-01 11:46 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	public ArrayList<Bill> getBillsForPatient(GregorianCalendar dateFrom, GregorianCalendar dateTo, Patient patient) throws OHServiceException {
Nice the idea to add @deprecate, for this method I would suggest `getBillsBetweenDatesWherePatient`

2020-09-01 11:46 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	public ArrayList<Bill> getBillsWithBillItem(GregorianCalendar dateFrom, GregorianCalendar dateTo, BillItems billItem) throws OHServiceException {
for this method I would suggest `getBillsBetweenDatesWhereBillItem`

2020-09-01 14:49 UTC, dbmalkovsky commented
OK; renamed the methods per suggestions; thanks.

BTW, I noticed the Javadoc reads for those methods with dates:
<pre>
	 * @param dateFrom the low date range endpoint, inclusive. 
	 * @param dateTo the high date range endpoint, inclusive.
</pre>
when calls into question the other discussion we had about date parsing and the use of `b.date >= :dateFrom and b.date < :dateTo` which the underlying code uses and is obviously not *inclusive* at the high end.

2020-09-01 15:12 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +		return getBillsBetweenDates (dateFrom, dateTo);
is the space before brackets intentional?

2020-09-01 15:12 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	public ArrayList<Bill> getBillsBetweenDates (GregorianCalendar dateFrom, GregorianCalendar dateTo) throws OHServiceException {
is the space before brackets intentional?

2020-09-01 15:14 UTC, mwithi commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
>  		return new ArrayList<Bill>(billRepository.findByDateBetween(TimeTools.getBeginningOfDay(dateFrom), TimeTools.getBeginningOfNextDay(dateTo)));
getBeginningOfDay(dateFrom) is _inclusive_ of dateFrom
getBeginningOfNextDay(dateTo) is _inclusive_ of dateTo

2020-09-01 15:15 UTC, mwithi commented
> which the underlying code uses and is obviously not _inclusive_ at the high end.

it is better to double-check what is happening here, but seems ok (see my [comment](https://github.com/informatici/openhospital-core/pull/194/files#r481221221)).

2020-09-01 15:27 UTC, dbmalkovsky commented
No the space was from my "replace" command having a trailing blank; now fixed; thanks.

2020-09-01 19:41 UTC, pviotti commented on src/main/java/org/isf/accounting/service/AccountingIoOperations.java
> +	@Deprecated
(TIL: from Java 9 you can add since and forRemoval attributes https://www.baeldung.com/java-deprecated#optional-attributes )

2020-09-01 19:42 UTC, pviotti approved these changes
Good call! LGTM.

2020-09-01 19:43 UTC, merged