OP-434 use parameterized tests for MATERNITYRESTARTINJUNE
informatici/openhospital-core pull request #320
Opened 2021-02-08 12:35 UTC by dbmalkovsky

Use parameterized testing method for MATERNITYRESTARTINJUNE with `true` and `false` values.

2021-02-09 08:30 UTC, mwithi requested changes
One variable has a wrong name.

Anyway I expect that some tests will fail because it is not always true that getNextYProg() returns YProg + 1.

Based on the MATERNINTYSTARTINJUNE flag it will if the admission date is before june, otherwise it will restart by 1 if it is the first admission in june.

I don't think we were testing in this way before but we should.

Thanks!

2021-02-09 08:30 UTC, mwithi commented on src/test/java/org/isf/admission/test/Tests.java
> +	public static Collection<Object[]> automaticlot() {
wrong variable name

2021-02-09 15:03 UTC, dbmalkovsky commented
I believe the current code will work for both values of MATERNINTYSTARTINJUNE now through the end of May of this year and then it will fail.

In AdmissionIoOperations.java the code is comparing **now** to **June**:
````
if (wardId.equalsIgnoreCase("M") && GeneralData.MATERNITYRESTARTINJUNE) 
   {
	if (now.get(Calendar.MONTH) < 6) 
````

I'll work on resetting the calendar in the test 😄

2021-02-09 18:31 UTC, dbmalkovsky commented
I tried multiple ways to manipulate the dates for MATERNITYRESTARTINJUNE testing but the only way that seemed to work is by adding a new method and `public static` variables specific for testing in `AdmissionIoOperations`.     In the process I found that the original tests for `getNextYProg()` never found any records (because of date issues) and always just returned `1`.

It might not be elegant but it works.

2021-02-10 21:56 UTC, mwithi approved these changes
maybe some Javadoc could help.
it's ok otherwise.
```
Results :

Tests run: 1164, Failures: 0, Errors: 0, Skipped: 2
```

2021-02-10 21:56 UTC, mwithi commented on src/main/java/org/isf/admission/service/AdmissionIoOperations.java
> +
we could add Javadoc to explain the testing purpose

2021-02-11 08:04 UTC, merged