OP-655 Use interface instead of concrete class
informatici/openhospital-core pull request #490
Opened 2021-09-14 12:56 UTC by dbmalkovsky

See OP-655

As usual some reformatting is included.

2021-09-16 21:01 UTC, mwithi requested changes
Small changes required

2021-09-17 06:49 UTC, dbmalkovsky commented on src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
> +	public List<Movement> getMovements(			String wardId,			GregorianCalendar dateFrom,			GregorianCalendar dateTo) throws OHServiceException {
Fixed

2021-09-17 06:49 UTC, dbmalkovsky commented on src/main/java/org/isf/therapy/service/TherapyIoOperations.java
> +				repository.findAllByOrderByPatientAscTherapyIDAsc();
Fixed

2021-09-17 07:12 UTC, mwithi approved these changes

2021-09-17 07:13 UTC, merged